abstract class UserListM {
  static const List users = [
    {
      'id': '0',
      'nameComp': 'Luciana da Silva',
      'name': 'Luciana',
      'city': 'São Paulo',
      'state': 'SP',
      'gender': 'Feminino',
      'married': 'Não',
      'smoker': 'Não',
      'doador': 'Não',
      'blood': 'O+',
      'son': 'Não',
      'worker': 'Sim',
      'year': '22',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '1',
      'nameComp': 'Mateus Pereira',
      'name': 'Mateus',
      'city': 'Curitiba',
      'state': 'PR',
      'gender': 'Masculino',
      'married': 'Não',
      'smoker': 'Não',
      'doador': 'Não',
      'blood': 'AB+',
      'son': 'Sim',
      'worker': 'Sim',
      'year': '32',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '2',
      'nameComp': 'Amanda de Lima',
      'name': 'Amanda',
      'city': 'Rio de Janeiro',
      'state': 'RJ',
      'gender': 'Feminino',
      'married': 'Sim',
      'smoker': 'Não',
      'doador': 'Não',
      'blood': 'B-',
      'son': 'Sim',
      'worker': 'Sim',
      'year': '24',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '3',
      'nameComp': 'Roger de Souza',
      'name': 'Roger',
      'city': 'Campinas',
      'state': 'SP',
      'gender': 'Masculino',
      'married': 'Sim',
      'smoker': 'Sim',
      'doador': 'Sim',
      'blood': 'O+',
      'son': 'Não',
      'worker': 'Não',
      'year': '42',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '4',
      'nameComp': 'Eduardo Goularte',
      'name': 'Eduardo',
      'city': 'Curitiba',
      'state': 'PR',
      'gender': 'Masculino',
      'married': 'Não',
      'smoker': 'Não',
      'doador': 'Não',
      'blood': 'O-',
      'son': 'Não',
      'worker': 'Sim',
      'year': '35',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '5',
      'nameComp': 'Tamires Medeiros',
      'name': 'Tamires',
      'city': 'Curitiba',
      'state': 'PR',
      'gender': 'Feminino',
      'married': 'Não',
      'smoker': 'Sim',
      'doador': 'Sim',
      'blood': 'AB-',
      'son': 'Sim',
      'worker': 'Sim',
      'year': '40',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
    {
      'id': '6',
      'nameComp': 'Helena Paes',
      'name': 'Helena',
      'city': 'Rio de Janeiro',
      'state': 'RJ',
      'gender': 'Feminino',
      'married': 'Sim',
      'smoker': 'Não',
      'doador': 'Não',
      'blood': 'A+',
      'son': 'Sim',
      'worker': 'Não',
      'year': '63',
      'phrase':
          '"Lorem Ipsum is simply dummy text of the printing and typesetting industry."',
    },
  ];
}
